# Generated by Django 5.1.2 on 2024-10-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
