# Generated by Django 5.1.2 on 2024-10-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_admin_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('A4', 'A4'), ('Letter', 'Letter')], default='A4', max_length=20)),
                ('pages', models.PositiveIntegerField()),
                ('copies', models.PositiveIntegerField()),
                ('print_type', models.CharField(choices=[('Black & White', 'Black & White'), ('Color', 'Color')], default='Black & White', max_length=20)),
                ('is_text_only', models.BooleanField(default=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('To Pick-up', 'To Pick-up'), ('Cancelled', 'Cancelled'), ('Refund', 'Refund')], default='Pending', max_length=20)),
                ('availed_free_printing', models.BooleanField(default=False)),
            ],
        ),
    ]
