# Generated by Django 5.1.2 on 2024-10-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_image',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='order',
            name='ref_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
