# Generated by Django 5.1.2 on 2024-10-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_order_is_text_only_order_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='print_type',
            field=models.CharField(choices=[('Black and White', 'Black and White'), ('Colored', 'Colored')], default='Black & White', max_length=20),
        ),
    ]
