# Generated by Django 5.1.2 on 2024-10-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a4_supplies', models.PositiveIntegerField(default=0)),
                ('letter_supplies', models.PositiveIntegerField(default=0)),
                ('legal_supplies', models.PositiveIntegerField(default=0)),
                ('blue_ink', models.PositiveIntegerField(default=0)),
                ('yellow_ink', models.PositiveIntegerField(default=0)),
                ('red_ink', models.PositiveIntegerField(default=0)),
                ('black_ink', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='document_type',
            field=models.CharField(choices=[('A4', 'A4'), ('Letter', 'Letter'), ('Legal', 'Legal')], default='A4', max_length=20),
        ),
    ]
