# Generated by Django 5.1.2 on 2024-10-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_supply_alter_order_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
