# Generated by Django 5.1.2 on 2024-11-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_contactmessage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('To Pick-up', 'To Pick-up'), ('Cancelled', 'Cancelled'), ('Pending Refund', 'Pending Refund'), ('Pending Payment', 'Pending Payment'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
    ]
