# Generated by Django 5.1.2 on 2024-11-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isFreePrintingAvailed',
            field=models.BooleanField(default=False),
        ),
    ]
