# Generated by Django 5.1.2 on 2024-11-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_user_isfreeprintingavailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isFreePrintingUsed',
            field=models.BooleanField(default=False),
        ),
    ]
