# Generated by Django 5.1.2 on 2024-11-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_discountvoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isForgetPassword',
            field=models.BooleanField(default=False),
        ),
    ]
