# Generated by Django 5.1.2 on 2024-11-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_user_isforgetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountvoucher',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_free_printing_availment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
