# Generated by Django 5.1.2 on 2024-11-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_discountvoucher_is_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Text Only', 'Text Only'), ('Text with Images', 'Text with Images'), ('Images Only', 'Images Only'), ('Images with Small Text', 'Images with Small Text')], default='Text Only', max_length=40),
        ),
    ]
