# Generated by Django 5.1.2 on 2024-11-07 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_requestrefund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_free_printing_availment',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
