# Generated by Django 5.1.2 on 2024-11-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_user_last_free_printing_availment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_free_printing_availment',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
