# Generated by Django 5.1.2 on 2024-11-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_user_last_free_printing_availment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='queue_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
