# Generated by Django 5.1.2 on 2024-11-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
