# Generated by Django 5.1.2 on 2024-11-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_admin_gender_admin_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='friday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='friday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='monday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='monday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='saturday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='saturday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='sunday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='sunday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='thursday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='thursday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='tuesday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='tuesday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='wednesday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='wednesday_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
