# Generated by Django 5.1.2 on 2024-11-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_admin_friday_end_admin_friday_start_admin_monday_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='friday_is_vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='monday_is_vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='saturday_is_vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='sunday_is_vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='thursday_is_vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='tuesday_is_vacant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin',
            name='wednesday_is_vacant',
            field=models.BooleanField(default=False),
        ),
    ]
