# Generated by Django 5.1.2 on 2024-11-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_printer_alter_order_print_type_order_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modalColor',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
