# Generated by Django 5.1.2 on 2024-11-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_user_modalcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('For Printing', 'For Printing'), ('For Pick-up', 'For Pick-up'), ('Cancelled', 'Cancelled'), ('Pending Refund', 'Pending Refund'), ('Pending Payment', 'Pending Payment'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
    ]
