# Generated by Django 5.1.2 on 2024-11-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='role',
            field=models.CharField(default='student', max_length=100),
        ),
    ]
