# Generated by Django 5.1.2 on 2024-11-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_logs_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='brand',
            field=models.CharField(default='Brand', max_length=100),
        ),
    ]
