# Generated by Django 5.1.2 on 2024-11-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_printer_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
