# Generated by Django 5.1.2 on 2024-11-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
