# Generated by Django 5.1.2 on 2024-11-18 11:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_delete_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='printer',
            field=models.CharField(default='Printer', max_length=100, verbose_name=api.models.Printer),
        ),
    ]
