# Generated by Django 5.1.2 on 2024-11-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_order_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='printer',
        ),
        migrations.AddField(
            model_name='order',
            name='printer_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='printer_name',
            field=models.CharField(default='Printer', max_length=100),
        ),
    ]
