# Generated by Django 5.1.2 on 2024-11-21 02:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_order_printer_order_printer_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountvoucher',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='discountvoucher',
            name='picture_format',
            field=models.CharField(default='png', max_length=100),
        ),
    ]
