# Generated by Django 5.1.2 on 2024-11-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_discountvoucher_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountvoucher',
            name='students',
            field=models.ManyToManyField(related_name='vouchers', to='api.user'),
        ),
    ]
