# Generated by Django 5.1.2 on 2024-11-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_discountvoucher_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trailpay_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
