# Generated by Django 5.1.2 on 2024-11-21 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_user_trailpay_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('top_up_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_image', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('ref_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
