# Generated by Django 5.1.2 on 2024-11-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
