# Generated by Django 5.1.2 on 2024-11-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_transaction_remark_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='logs',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
