# Generated by Django 5.1.2 on 2024-11-26 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='printer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.printer'),
        ),
    ]
