# Generated by Django 5.1.2 on 2024-11-26 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_message_printer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.printer'),
        ),
    ]
