# Generated by Django 5.1.2 on 2024-11-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_message_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='qr_code',
            field=models.URLField(blank=True, null=True),
        ),
    ]
