# Generated by Django 5.1.2 on 2024-11-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_message_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='printer',
            new_name='printer_location',
        ),
    ]
