# Generated by Django 5.1.2 on 2024-11-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_rename_printer_message_printer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
