# Generated by Django 5.1.2 on 2024-11-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_logs_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
