# Generated by Django 5.1.2 on 2024-11-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_logs_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('F2F', 'Face to Face'), ('TrailPay', 'TrailPay'), ('GCash', 'GCash'), ('Other', 'Other Online Method')], max_length=20, null=True),
        ),
    ]
