# Generated by Django 5.1.2 on 2024-11-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secondaryModalColor',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
