# Generated by Django 5.1.2 on 2024-11-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_user_secondarymodalcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avail_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
