# Generated by Django 5.1.2 on 2024-11-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_user_avail_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fontColor',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
