# Generated by Django 5.1.2 on 2024-12-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_user_fontcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pick_up_time_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
