# Generated by Django 5.1.2 on 2024-12-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_order_pick_up_time_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pick_up_time_date',
        ),
    ]
