# Generated by Django 5.1.2 on 2024-12-03 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_remove_order_pick_up_time_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pick_up_time_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
