# Generated by Django 5.1.2 on 2024-12-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_order_pick_up_time_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='brand',
            field=models.CharField(blank=True, default='Brand', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='total_sales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='used_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
