# Generated by Django 5.1.2 on 2024-12-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_user_avail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modalColor',
            field=models.CharField(default='#dbf8ff', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='secondaryModalColor',
            field=models.CharField(default='#f4f4f4', max_length=20),
        ),
    ]
