# Generated by Django 4.2.7 on 2024-12-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_alter_user_modalcolor_alter_user_secondarymodalcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profileImage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='signature',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
