# Generated by Django 4.2.7 on 2024-12-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_supply_printer_location'),
        ('api', '0077_order_payment_method'),
    ]

    operations = [
    ]
