# Generated by Django 4.2.7 on 2024-12-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_merge_20241223_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='printer_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
