# Generated by Django 4.2.7 on 2024-12-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_message_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='college_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='student_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
