# Generated by Django 4.2.7 on 2025-01-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_alter_order_document_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='status_estimated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
